### ISSUE TITLE
cookieValidationKey is not generated after installation

### ISSUE THREAD

**Issue by DavertMik** [yiisoft/yii2-app-basic#69]
### What steps will reproduce the problem?

```
composer install
```
### What's expected?

Security code is generated and inserted in `web.php`
### What do you get instead?

I had to put it manually.
### Additional info

PHP version: 7.0.4
Composer version 1.2-dev (08ef916beded8c738be11acc4f463c450e277d64) 2016-06-06 10:22:06
#### Php modules

```
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mongodb
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

**Comment by rob006** [comment]
`composer install` doesn't trigger `cookieValidationKey` generation, right now it is only generated on `composer create-project`. #66 changes that.

**Comment by samdark** [comment]
This one should be fixed by recently released yii2-composer plugin.

**Comment by rob006** [comment]
@samdark This template does not use new features of yii2-composer, so it is not solved at all.

**Comment by SilverFire** [comment]
Fixed by http://hotline.ua/computer-myshi-klaviatury/a4tech_kv-300h/prices/
